name: Merge PRs

on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        uses: finnp/delete-merged-branch@master
        with:
          branches: "!main, !production, *"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"